### PR TITLE
installdata: remove PackageInstaller if its in priv-app too

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by invisiblek** [comment]
it might be better to leave app/ and add priv-app/, just to make sure it gets killed off

**Comment by mfonville** [comment]
Yeah. Both locations is safer. If you'd update the patch I will pull that

**Comment by mfonville** [comment]
Thanks!

**Comment by airend** [comment]
Thanks, @invisiblek! I thought I was going crazy with things not finishing booting, but all is finally well with your fix.

**Pull request merged**
