### PR TITLE
Replace Instances of CyanogenMod

### LINKED ISSUE #512: gapps removal keywords - overdue cleanup needed
First,
StorageManagerStock should automatically remove if StorageManagerGoogle is removed.  If it is being removed, the wiki and Aroma Gapps screens should reflect so.

All references to CMxxx stuff needs to be removed.  CyanogenMod is dead and it's confusing.
    
    CMAccount		dead
    CMAudioFX		rename to LAudioFX
    CMBugReport		rename to LBugReport
    CMFileManager		rename to LFileManager
    CMMusic			rename to LMusic
    CMSetupWizard		rename to LSetupWizard
    CMUpdater		rename to LUpdater
    CMWallpapers		I don't know if LineageOS has a wallpaper package?

Also, several of the wiki and Aroma removals are dead in Android Nougat- perhaps even lollipop.

Are these apps still relevant in Nougat and on Nougat-based custom ROMs?  It just makes it look silly.  I don't know why this is even a static list.  You might just want to have OpenGapps support removing by package names, dynamically load a list of what is installed, or something and rather than a hardcoded list of things to remove.
    
    BasicDreams		relevant today?
    DashClock		relevant today?
    FMRadio			?
    Galaxy			Nougat doesn't have this
    HoloSpiral		Nougat doesn't have this
    LiveWallpapers		Nougat doesn't have this
    LockClock		relevant today?
    NoiseField		Nougat doesn't have this
    Phasebeam		Nougat doesn't have this
    PhotoPhase		Nougat does have this thanks @richiksc 
    PhotoTable		Nougat does have this thanks @richiksc 
    Studio			Nougat doesn't have this.  Wasn't this like Android Gingerbread?
    SykoPath		relevant today?
    Themes			LineageOS doesn't have this.  Definitely not Nougat
    VisualizationWallpapers	Nougat doesn't have this
    WhisperPush		No one has this.  Wasn't this like CyanogenMod... Froyo or something?

### PR DESCRIPTION
**Pull request by richiksc**
Partially fixes #512

Changes:
- Replace instances of the "CM" prefix (excluding CMAccount) in installer and aroma files.

### CODE REVIEW

**Comment by richiksc** [comment]
@mfonville ?

**Comment by osm0sis** [comment]
As far as I know they're called CM where in the ROM they're still called CM. Lineage won't complete the rebranding for the majority of their system apps until LOS15.

**Comment by richiksc** [comment]
I just renamed the references not the actual pointers to the apps

**Comment by osm0sis** [comment]
The references should match the app names though. @mfonville will of course make the final call, but I think this might have to wait.

**Comment by SimJoSt** [comment]
I agree.
Also, I believe the abbreviation for LineageOS is LOS not L.

**Comment by osm0sis** [comment]
When I made the first PR for new Lineage app removals I brought up L vs LOS as the abbreviation to @mfonville and he preferred L to keep it simple.

**Comment by pr030880** [comment]
In the most recent Lineage ROMs (14.1) they renamed the CMUpdater to Updater. Meaning Open GApps won't remove the Updater with CMUpdater anymore. The folder name changed as well from ../CMUpdater to ../Updater

**Comment by osm0sis** [comment]
CMUpdater has been replaced by a fully revamped Lineage Updater, so a new keyword for LUpdater is required. You can file a PR for this if you like.

**Pull request closed without merging**
