### PR TITLE
Convert bashisms to POSIX

### PR DESCRIPTION
**Pull request by rhansen**

### CODE REVIEW

**Comment by nezorflame** [comment]
@rhansen hi! Could you please resolve the conflicts?

**Comment by rhansen** [comment]
Done.

**Comment by nezorflame** [comment]
@mfonville take a look as well please

**Comment by mfonville** [comment]
Thank you!
Did you test, so that we are sure there a no typos? :-)

**Comment by rhansen** [comment]
Yes.

**Comment by mfonville** [comment]
Thanks!

**Comment by nezorflame** [comment]
@mfonville - there are submodule changes in this PR as well. Will this affect anything, or can we just ignore that?

**Comment by rhansen** [comment]
I opened PR #853 to undo the submodule changes. I don't know what happened. Maybe `git rebase` doesn't handle submodules well?

**Pull request merged**
