### PR TITLE
Create de.lang

### PR DESCRIPTION
**Pull request by xdevs23**
Fixes Nothing.

Changes:
- Add german language to aroma res
-
-

@opengapps/developers

### CODE REVIEW

**Comment by mfonville** [comment]
@raulpetru could you take a look at this?

**Comment by mfonville** [comment]
We were not aware that AROMA-installer already contained several language files. We will merge them ASAP.

**Comment by xdevs23** [comment]
I think these are not the full translations

**Comment by mfonville** [comment]
@xdevs23 They are indeed not, they only cover the aspects of AROMA-Installer itself, not our aroma-specific config.

Unfortunately Aroma-Installer is no longer maintained. We are already waiting ages on a new one based on the new libaroma; but @raulpetru is also planning a web-based config-generator, that should make things more easy and translatable.

**Comment by xdevs23** [comment]
Alright. If I do not notice once it is fully translatable, please notify me so I can translate it :)

**Comment by mfonville** [comment]
will do :+1:

**Comment by xdevs23** [comment]
Great.

**Pull request merged**
