### PR TITLE
Add FlymeOS Launchers to launcher removal list

### PR DESCRIPTION
**Pull request by AlexLartsev19**
Fixes nothing.

Changes:
- Add FlymeOS Launchers to launcher removal list

@opengapps/developers

### CODE REVIEW

**Comment by mfonville** [comment]
Hi @AlexLartsev19 ,

thanks for the PR. Could you inform me on which ROMs these launchers are installed by default?

**Comment by nvenasquez** [comment]
If you can also add Perception launcher to be removed and replaced by Google Launcher on Stock Gapps (Perception Launcher is Nameless ROM default launcher)

**Comment by mfonville** [comment]
@nvenasquez if you could identify each launcher's ROM (for our documentation and history) and make an extra commit for Perception Launcher, you can squash them together in the PR.
https://github.com/blog/2141-squash-your-commits

**Comment by AlexLartsev19** [comment]
Hi @mfonville ,
These launchers installed on FlymeOS.It's a official ROM on Meizu devices and custom ROM on some devices, like a Nexus 5, OnePlus One, SGN 3. If you want see all devices compatible with FlymeOS see [this](http://www.flyme.cn/firmware.html).

**Comment by mfonville** [comment]
@AlexLartsev19 thanks for the info!

**Pull request merged**
