### PR TITLE
Restore ZipSigner and fix custom keys signing

### PR DESCRIPTION
**Pull request by osm0sis**
topjohnwu got a minute to look at the zipsigner code and resolved the issue from 2.1, confirmed working locally via command prompt `java -jar zipsigner-2.2.jar custom.x509.pem custom.pk8 test.zip test-signed.zip`. Also tested and working with .x509.der instead of .pem. Should work with the buildbot now. 👍

### CODE REVIEW

**Comment by mfonville** [comment]
Unfortunately there are still issues, even when having plenty of diskspace on the machine, I get this error on buildbot when signing arm64 8.1 aroma:
```
Packaging and signing /home/maarten/Development/opengapps/out/open_gapps-arm64-8.1-aroma-20180527.zip...
INFO: using opengapps.org.x509.pem as certificate file
INFO: using opengapps.org.key.pk8 as cryptographic key file
Exception in thread "main" java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:332)
	at com.topjohnwu.utils.ZipAdjust.adjust(ZipAdjust.java:60)
	at com.topjohnwu.utils.ZipAdjust.adjust(ZipAdjust.java:18)
	at com.topjohnwu.utils.SignAPK.signZip(SignAPK.java:92)
	at com.topjohnwu.utils.ZipSigner.main(ZipSigner.java:47)
```

To which device do you think the script refers that it has no diskspace?

@osm0sis @topjohnwu

**Comment by NicholasBuse** [comment]
Is it that you need to allocate additional RAM in the java call? (e.g. -Xmx2048m)

**Comment by mfonville** [comment]
I think I found the problem, I have little space on `/tmp` on the root partition and I think that is where zipsigner makes the temporary files.

**Comment by osm0sis** [comment]
Glad you got it resolved on the build bot server-side. :+1:

**Pull request merged**
