### PR TITLE
Create makefile.yml

### PR DESCRIPTION
**Pull request by husseinlashin**
Fixes #.

Changes:
-
-
-

### CODE REVIEW

**Review by husseinlashin — COMMENTED** [review]
nicexgfc###

**Review by husseinlashin — COMMENTED** [review]
> 
WhatsApp Image 2022-09-22 at 03 28 15 (4)

**Comment by husseinlashin** [comment]
n

**Comment by osm0sis** [comment]
Wow. Amazing work.

**Pull request closed without merging**
