### PR TITLE
Update partitions used by installer and backup scripts

### PR DESCRIPTION
**Pull request by z3DD3r**
Changes:
- Added support for /system_ext partition (mount and search apps for deletion)

### CODE REVIEW

**Review by nezorflame — APPROVED** [review]
LGTM

**Comment by osm0sis** [comment]
Isn't /persist still potentially used for .gapps-config?

**Comment by z3DD3r** [comment]
> Isn't /persist still potentially needed for .gapps-config? It was being used since there was no other option on some devices (no /data decryption, no /cache) and .gapps-config is tiny. Problems only arose when TWRP was completely filling /persist with logs.

The idea behind removing /persist is that no one should touch it if they don't really need to. In my experience, there have been many problems after users accidentally deleted data from this partition. I understand that this is not an opengapps problem. But if we will not support this partition, then no one will use it and will not break anything...

Your point about /data decryption and /cache is valid! But how user will be able install opengapps in such case? The only way i can imagine is otg. But in case in of otg, gapps-config can be placed near the flashable zip...

Anyway, change for /persist can be easily dropped from this PR. Let know what do you think about it and how i should proceed with this change.

**Comment by osm0sis** [comment]
I think the intention was it's a location to store the .gapps-config on-device, but the zip would need to be sideloaded, so yes, I think it should still be supported. Magisk supports it for sepolicy as well for similar reasons. As far as I know the only issues were with TWRP using it for logs and filling it up.

**Comment by z3DD3r** [comment]
@osm0sis,
Got it! I have removed change for /persist partition

**Review by osm0sis — APPROVED** [review]

**Review by mfonville — APPROVED** [review]

**Comment by mfonville** [comment]
Thanks!

**Pull request merged**
