### PR TITLE
Confirm without pressing enter

### PR DESCRIPTION
**Pull request by bgiesing**
Will confirm without pressing enter, so if you hit `y` it will just do it now instead of having to hit `y[ENTER]`

@mfonville @rapperskull

### CODE REVIEW

**Comment by mfonville** [comment]
I am not sure if that is desired behaviour. I don't have a shell here. But how does e.g. apt-get or other *nix-applications handle this? Does it wait for enter?

**Comment by bgiesing** [comment]
@mfonville Apt-Get doesn't wait and neither does most other apps.

**Comment by mfonville** [comment]
I did check now via juicessh on my server. And apt-get does actually wait for enter. And openssh too...
Did you maybe tweak something in you own pc somewhere?

**Comment by bgiesing** [comment]
No but I know it does vary based on App.

On Fri, Aug 14, 2015, 11:45 PM mfonville <notifications@github.com> wrote:

> I did check now via juicessh on my server. And apt-get does actually wait
> for enter. And openssh too...
> Did you maybe tweak something in you own pc somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/pull/90#issuecomment-131293512>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljrFqwzAUAL_GHsPTs_QkDRqcOhmaQKDQUrpJT5LlOomL40Dar29xb7jxuOiIPGM9uKf2cJ_0-DofF3mbXqa33buiRziOe8nNvvm8duXjWcLY9T_tUk7dXPpKwsUP502_mqdLXVwWIRqtJJEAna2WyRAaFBYoqCxMPbs5fZ2_K9wCaKOt18gBDNlMKrNBHRg5SmCf2AsM2jcIHhqMFjnDP0KIREZFZdELspyAgDxx_Fta85t-WMo9rFOLq7D9BTC7RLk>

**Comment by mfonville** [comment]
Would you mind if I don't pull this one then? The impact of commits and pushes can be high, so I prefer the defaults to be 'negative' and that one is kept conscious of what is being committed and pushed to the repo.

**Comment by bgiesing** [comment]
I don't mind.

On Sun, Aug 16, 2015, 5:34 AM mfonville <notifications@github.com> wrote:

> Would you mind if I don't pull this one then? The impact of commits and
> pushes can be high, so I prefer the defaults to be 'negative' and that one
> is kept conscious of what is being committed and pushed to the repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/pull/90#issuecomment-131522262>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljk1PwzAQRH9NcqzWzmZtH3xooSpSihAIQcsF7fqjCW0Jilok-PVYYQ4jzRyeXvREHHQ9-Jtldx3N8eXI7fM730ufdk-q2a7S7eumU2p8uKv06m3_-_0x7bptp-XTrB8rhDMPp8Vh7jCe695zi40ImoQui0sQMymbtAsZODA19eSn9HX6KTgAY41jYwmjZkRLUSGg2EhGpEUDTgcKrYQmQ5llZfiPUipZ7XT5WJELCQiIKcSiNOMXh-HSX2WWuvhKL_8AeaVEsQ>

**Pull request closed without merging**
