### PR TITLE
Android R bringup

### PR DESCRIPTION
**Pull request by nezorflame**
Initial bringup, probably more changes will follow soon.

Corresponding PR's for the APKs:
[all](https://gitlab.opengapps.org/opengapps/all/-/merge_requests/37)
[arm](https://gitlab.opengapps.org/opengapps/arm/-/merge_requests/17)
[arm64](https://gitlab.opengapps.org/opengapps/arm64/-/merge_requests/22)
[x86](https://gitlab.opengapps.org/opengapps/x86/-/merge_requests/9)
[x86_64](https://gitlab.opengapps.org/opengapps/x86_64/-/merge_requests/4)

### CODE REVIEW

**Comment by soredake** [comment]
Any progress on this?

**Comment by nezorflame** [comment]
Slow but steady. You can watch test releases at the [main XDA thread](https://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/page692) or directly at SourceForge's [test](http://sourceforge.net/projects/opengapps/files/arm64/test/) folder (ARM64-only for now).

**Comment by althafvly** [comment]
PR for arm
https://gitlab.opengapps.org/opengapps/arm/-/merge_requests/29

**Comment by nezorflame** [comment]
@althafvly thanks, merged.

**Comment by nezorflame** [comment]
New builds (including fixes from #902 and #903) are up on SourceForge: [ARM](https://sourceforge.net/projects/opengapps/files/arm/test/20210108/) | [ARM64](https://sourceforge.net/projects/opengapps/files/arm64/test/20210108/)

**Comment by nezorflame** [comment]
New build, including the fixes from #905 (this time without the fixes from #902 and #903) will be up on SourceForge in a few minutes.

There is a new PlayStoreOverlay specific for R to allow Google apps to be installed from non-Play Store locations (thanks to `@coin3x` and `@r6680jc` from the Telegram discussion group!).

Also we should now have Chrome and Webview working properly due to the return of the SDK29+ verions of these apps.

**Comment by soredake** [comment]
Files Go is now default files app on android 11, can it be added?
https://github.com/opengapps/opengapps/issues/567#issuecomment-779427996

**Comment by soredake** [comment]
Can this be merged? Android 11 was released in September last year, and seven month later? Still no official support.

**Comment by nezorflame** [comment]
No, it can't. It will be merged when it's ready, and it's not ready right now.

Will probably take one-two more test builds before release, so shouldn't 
take long, but as always - no exact ETA.

Best regards,
Danilkin Ilya
_____________________

С уважением,
Данилкин Илья
soredake ***@***.***> 18 марта 2021 г. 17:10:45 написал:

**Comment by soredake** [comment]
@nezorflame how about google files for r? Will it be added?

**Comment by lukasz1992** [comment]
@nezorflame what are the current issues right now? Is it possible to somehow help with testing?

**Comment by Ronald-G-Andrade** [comment]
> No, it can't. It will be merged when it's ready, and it's not ready right now. Will probably take one-two more test builds before release, so shouldn't take long, but as always - no exact ETA.

Dear brother, thanks for your excellent work. I hope Android 11 OpenGapps will be released soon 👍🏻

**Comment by nezorflame** [comment]
We're merging this, but only for `pico` and `nano` releases right now.
Support for the other packages will be added soon.

**Comment by Ronald-G-Andrade** [comment]
> 
> 
> We're merging this, but only for `pico` and `nano` releases right now.
> Support for the other packages will be added soon.

Big thanks brother 👍🏻 Please add it to the main page (opengapps.org) 😃

**Comment by nezorflame** [comment]
> > We're merging this, but only for `pico` and `nano` releases right now.
> > Support for the other packages will be added soon.
> 
> Big thanks brother 👍🏻 Please add it to the main page (opengapps.org) 😃

As soon as it's built, sure.

**Pull request merged**
