### PR TITLE
opengapps: Support Addon v2

### PR DESCRIPTION
**Pull request by TheScarastic**
Add support for addon support on a/b devices

### CODE REVIEW

**Comment by TheScarastic** [comment]
works fine on tissot

**Comment by logan2611** [comment]
Works on Pixel XL running LOS 15.1 August 7th 2018

**Comment by npjohnson** [comment]
Works on nash and taimen

**Comment by Kirk1984** [comment]
I also tried it on tissot. Works fine.

**Comment by vkbhanwariya** [comment]
Working perfectly on Tissot 😍

**Comment by SpasilliumNexus** [comment]
Might want to wait until I submit a pull for the [Android 9.0 bring-up](https://github.com/SpasilliumNexus/opengapps/commits/android-9.0), in which I'll very likely do this weekend. I've modified those files in said bring-up, but yet have no idea what needs to be changed for addon.d v2, as I don't have an A/B device to test changes with.

**Comment by dende** [comment]
Would be great if this commit could be merged asap.

**Comment by SpasilliumNexus** [comment]
@dende if this is merged now, the 9.0 bring-up I'm submitting pull requests for tomorrow will have parts of the installer that ARE NOT v2, and I've posted the reason why, right above your post...

A few more days wait will not hurt.

**Comment by npjohnson** [comment]
@SpasilliumNexus Freshly rebased change here: https://github.com/npjohnson/opengapps/commit/014fcd6d7038ced477838ebfa6e2a1ac32a07261

**Comment by NicholasBuse** [comment]
I just resolved the current conflicts in the same manner as @npjohnson, it was easier this way for the 3 line and 6 typo corrections...

**Comment by NicholasBuse** [comment]
@npjohnson I did just notice that you had some inconsistencies ("/$SYS" vs "$SYS, left in a "/system". etc.)

I left specific comments on your repo commit...

**Comment by npjohnson** [comment]
@NicholasBuse, I probably missed some.

But good to see you got it fixed up and merged!

**Pull request merged**
