### PR TITLE
Add option to keep the AOSP Dialer when Google Dialer is installed.

### PR DESCRIPTION
**Pull request by mwyau**
Allow using the +DialerStock option to keep the AOSP Dialer in stock/super/aroma.

### CODE REVIEW

**Comment by SpasilliumNexus** [comment]
I can confirm that this works on stock build of OpenGApps. I myself don't use Aroma, so I am unable to test, but the code looks good to me.

**Comment by viggy96** [comment]
Can this be merged already...

**Comment by SpasilliumNexus** [comment]
What's wrong with installing DialerFramework, which keeps the stock dialer, then installing Google Dialer from the Play Store for now...?

**Comment by NicholasBuse** [comment]
Can some on this thread update the wiki for this?

Thanks!

**Comment by mwyau** [comment]
I have added the entry to the wiki. Nice to have it finally merged so I don't have to manually editing my script for each update.

**Comment by SpasilliumNexus** [comment]
In addition, I've added a warning about installing `DialerGoogle` on Android 8.0+ custom ROMs.

**Comment by viggy96** [comment]
There doesn't appear to be another build by the buildbot after this was merged... Can we manually trigger a build please to put this out there as soon as possible?

**Comment by ALTracer** [comment]
@viggy96 , I compiled a 20180721 version at home, you can check the package at [my dedicated RPi3](https://altracer.onthewifi.com/LineageOTA/builds/opengapps/). Peeking at shell scripts would be enough if you mind installing zips from random strangers on teh internets.

**Pull request merged**
