### PR TITLE
Strip binaries

### PR DESCRIPTION
**Pull request by arter97**
Especially for tar, those binaries are shipped to the zip files.
Reducing the file size for these are important.

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
@mfonville Take a look at this please :)

**Comment by mfonville** [comment]
Thanks for the PR, could you explain to me how you did strip the binaries and the lib? So that we could reproduce it?

**Comment by arter97** [comment]
find . -type f -exec grep {} \; | grep "not stripped" | grep -v "relocatable"
will give you which files are not stripped.
And you can just do "strip" to the following files.
(e.g. arm-linux-androideabi-strip /path/to/file)

**Comment by mfonville** [comment]
thanks!

**Comment by mfonville** [comment]
@yashdsaraf fyi the stripping of the binaries

**Pull request merged**
