### PR TITLE
installer: Wrap the OpenGApps logo to support Android Recovery

### PR DESCRIPTION
**Pull request by AdrianDC**
* Without leading characters, the 'ui_print' calls strip every
   leading spaces, and wrapping with \', \" or \ prints them

### CODE REVIEW

**Comment by AdrianDC** [comment]
Different solutions welcomed, but this is a good start IMO.

**Comment by AdrianDC** [comment]
@osm0sis

**Review by nezorflame — APPROVED** [review]

**Comment by nezorflame** [comment]
LGTM.
WDYT @mfonville @osm0sis ?

**Comment by mfonville** [comment]
What does Android Recovery do with ASCII-code 255, the non-breaking space? Does it print it or does it also strip it?

**Comment by osm0sis** [comment]
Oof, couldn't Lineage just make Android Recovery display them like TWRP always has?

**Comment by osm0sis** [comment]
> What does Android Recovery do with ASCII-code 255, the non-breaking space? Does it print it or does it also strip it?

Just tested, it shows as ?, unfortunately.

**Comment by mfonville** [comment]
Would it make sense to file a bug report with Lineage to ask them to display like TWRP and legacy CWM and not stripping output in their recovery? As @osm0sis mentioned, why couldn't they just stick to the same behavior that was already many years in place and wasn't broken to begin with?

**Comment by osm0sis** [comment]
Further, I just tried the following in a zip:
```
  i=0;
  while [ $i -lt 400 ]; do
    ui_print "$(printf "%b" "\0$i")     test $i"
    i=$((i +1));
  done;
```

And unfortunately there aren't any viable blank space candidates to prepend to an existing line and keep Lineage from stripping the leading space.

**Comment by osm0sis** [comment]
I'm going to set this back to #wontfix unless anyone has anything else to add?

**Pull request closed without merging**
