### PR TITLE
Batch: pull request compilation of tweaks, fixes, additions, and bringup

### PR DESCRIPTION
**Pull request by SpasilliumNexus**
**installer: add stock wallpaperpicker (wallpapersstock) to optional remove list**
Fixes https://github.com/opengapps/opengapps/issues/614

Changes:
- installing google wallpapers will automatically remove stock/aosp wallpaperpicker
- stock/aosp wallpaperpicker also be can removed by adding keyword `wallpapersstock` to gapps-config or selected in aroma when not installing google wallpapers
- clarify entries of `"wallpaper"` in aroma as it referring to `"google wallpapers"`

To-do:
add `wallpapersstock` keyword to wiki.

**remove duplicate if statement in installer, on't > don't in aroma**
Changes:
- there are two entries of the following in `inc.installer.sh`. i have removed one of them:

> If we're NOT installing search then we MUST REMOVE pixellauncher from  $gapps_list (if it's currently there)
>  if ( ! contains "$gapps_list" "search" ) && ( contains "$gapps_list" "pixellauncher" ); then
>    gapps_list=${gapps_list/pixellauncher};
>    install_note="${install_note}pixellauncher_msg"$'\n'; # make note that Pixel Launcher will NOT be installed as user requested
>  fi;

- in `inc.aromadata.sh`, the letter `d` was missing for the description for googletts

**installer: search for gapps-config in more locations (/data)**
Changes:
- organize the list of locations
- also add additional search locations in /tmp/install

To-do:
add note of these locations in the wiki.

**installer: remove extraneous space for setupwizardtablet**
Changes:
- there was an extra space after the entry. removed to avoid any installation issues

### CODE REVIEW

**Comment by VincentJoshuaET** [comment]
Can you also add this issue: https://github.com/opengapps/opengapps/issues/618

Thanks

**Comment by SpasilliumNexus** [comment]
As for Google Sounds Picker, it can be found on APKMirror: https://www.apkmirror.com/apk/google-inc/sounds/sounds-1-0-4264627-release/sounds-1-0-4264627-2-android-apk-download/

For now, OpenGapps doesn't accept it due to the certificate (signature?) not being in OpenGapps' whitelisted certificates.

This app is meant to replace the stock Media Storage sounds picker app, but Media Storage is not removed as it is essential for Android to scan media.

Screenshots:
[Android System](https://i.imgur.com/2igRCWa.png)

[Media Storage sound picker](https://i.imgur.com/NK0q25P.png)

[Google Sounds picker](https://i.imgur.com/CmrvFUA.png)

**Comment by SpasilliumNexus** [comment]
@VincentJoshuaET Unfortunately, I'll leave that up to someone else who can figure out how to implement it, as I am completely stumped on how to go about it.

**Comment by rcmaehl** [comment]
@SpasilliumNexus I'm going to advocate for merging of #618 as well as on a large amount of ROMs replacement of the google dialer and dialer framework causes a Denial of Service for Emergency calls.

**Comment by VincentJoshuaET** [comment]
Have you tested all these changes? Can you upload an unofficial super test build for 8.1 arm64? Thanks.

**Comment by FayneAldan** [comment]
Why was this closed...?

**Comment by SpasilliumNexus** [comment]
Most of this are in the Pie bringup that I will submit a pull for after enough testing https://github.com/SpasilliumNexus/opengapps/commits/android-9.0

**Pull request closed without merging**
