### PR TITLE
installer: Fix support for Android 11 Recovery with system as root

### PR DESCRIPTION
**Pull request by AdrianDC**
* Currently, if we install OpenGApps from an Android 11 recovery,
   like Lineage Recovery (from LineageOS 18.1 releases), the
   installation will fail due to 0 bytes of free space available,
   and the /system/bin/ recovery binaries from system as root
   will be lost as the system partition is mounted to /system

 * To avoid a system as root breakage, acquire the system source
   and mount it to /system_root instead, and if mounted, ensure
   it is a system as root partition, otherwise we fallback
   to the ANDROID_ROOT mounting point as it used to be

### CODE REVIEW

**Comment by AdrianDC** [comment]
osm0sis

**Comment by althafvly** [comment]
Android -11 Lineage recoveries needs this support

@nezorflame can you check opengapps gitlab. I have registered there, so i can pull request arm changes for eleven

**Comment by nezorflame** [comment]
Thanks for your contribution!
So far seems OK, but need a bit more insight here.
@mfonville @osm0sis please take a look as well.

**Comment by nezorflame** [comment]
I'll also need you to test a build with these changes on two devices - with the described setup and without it (maybe an A-only device or some legacy one).

**Comment by mfonville** [comment]
Thanks! This definitely needs some testing and review by @osm0sis :-)

**Comment by AdrianDC** [comment]
I plan to do some more minor changes, will have time for it in the coming days. Thanks.

**Comment by osm0sis** [comment]
Hmm I'm currently working through this for AK3 on LOS 18.1 Recovery and I see on dynamic partition devices that /system_root, /system and / are no longer in /etc/fstab so I don't think this case is covered yet.

**Comment by osm0sis** [comment]
Alright, I've been informed that /dev/block/mapper gets setup when a zip is flashed, so that's all good, but I still don't see how the fstab fallback could work. I've just finished my fixes for AK3 and they work on LOS 18.1 Recovery and TWRP_10 in my testing, so perhaps Open GApps could adapt those instead?

Also worth mentioning the concern above about leaving a working shell isn't really important since Open GApps bundles its own busybox which is used instead, similar to Magisk and AK3, but I have attempted to ensure there's always a working underlying shell anyway by reorganizing when the apex mounts happen. :+1:

https://github.com/osm0sis/AnyKernel3/commits/master

**Comment by mfonville** [comment]
@osm0sis I think following your fixes for AK3 sounds good. Will you make a new PR for that?

**Comment by mfonville** [comment]
@AdrianDC could you check @osm0sis's PR?

**Comment by AdrianDC** [comment]
I'll try to have a look at these within the week, but not sure when yet.

@osm0sis 's PR looks OK to me, however I think it doesn't cover the /etc/fstab extraction part of this PR,
meaning the fallback implementation done in OpenGApps to use the ".../system" partition
does not support non-standard situations (for example, "System" here).

**Comment by osm0sis** [comment]
What do you mean, it's /dev/block/<something>/System on some devices?

**Comment by AdrianDC** [comment]
Yes, the same thing applies to bootimage partitions, for example this is what SuperSU (or now Magisk) used to do:
```
for PARTITION in kern-a KERN-A Kernel kernel KERNEL boot BOOT lnx LNX; do
  BOOTIMAGE_PATH=/dev/block/by-name/${PARTITION};
```

You're correct, the `mount /system` then `mount --move /system /system_root` is supposed to work, however,
the `mount /system` itself was masking the /system/bin/mount binaries, thus breaking most following shell commands
and leaving the device in a rather bad situation were only launched things still work.

I'd have to test again when I can, but I'd expect the same overlap behaviour.

**Comment by osm0sis** [comment]
The `mount /system` is actually intentional, and doesn't break anything for Open GApps since all is within Open GApps' included busybox ash sub-shell with applets in the $PATH, that said, I've adjusted when /apex gets mounted now, so that even when /system is mounted the actual /system/bin binaries now actually run, so there shouldn't be a gap of underlying shell breakage.

**Pull request closed without merging**
