### PR TITLE
Move installer.sh body to a separate template file

### PR DESCRIPTION
**Pull request by rhansen**
This will make it easier to make future changes.

### CODE REVIEW

**Comment by nezorflame** [comment]
@rhansen thanks for your contribution! @mfonville mind taking a look?

**Comment by rhansen** [comment]
Friendly ping.

**Comment by mfonville** [comment]
Thanks @rhansen this indeed greatly improves the readability and maintainability of the script.

Did you do extensive testing with your changes (e.g. building all the variants/archs/apis that exist)?

**Comment by rhansen** [comment]
I did not do any extensive testing—I only diffed the resulting installer.sh script for a single variant/arch/API.

**Comment by rhansen** [comment]
Is there a make target that generates just the installer.sh for each supported combination (no expensive packaging operations) so I can easily diff before and after?

**Comment by rhansen** [comment]
I generated installer.sh with and without this change for every supported combination. The only diffs are comments and blank lines: [diff.txt](https://github.com/opengapps/opengapps/files/4618265/diff.txt)

**Comment by nezorflame** [comment]
LGTM

**Comment by mfonville** [comment]
Thanks! I will merge it in :-)

**Pull request merged**
