### PR TITLE
Run ch_con on every copied file

### LINKED ISSUE #355: Incorrect SELinux labels after flashing OpenGapps
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

[ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
[ ] The issue is part of The Open GApps Project scope _(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))_

_If Open GApps compilation fails:_
[ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

_If Open GApps installation fails:_
[ ] Is the issue reproducible using the latest version of your recovery?
[ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? _(other recoveries are only best-effort)_

_If receiving force closures after Open GApps installation:_
[ ] The issue is **NOT** an error within one of the bundled Google applications itself _(verify by e.g. installing the application from the Play Store instead)_
[ ] The issue is reproducible on clean (=wiped /data/ partition) installation
[ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
[ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
So I am labeling some stuff in /system/lib and after flashing OpenGapps package it's relabeled to u:object_r:system_file:s0

**Reproduction Steps:**
1. Flash a CM build that labels anything in /system/lib/
2. Flash OpenGapps
3. Label is set to u:object_r:system_file:s0 instead of what it was set before

**Expected behavior:**

I guess labels should be set on specific files not recursively on whole /system/lib

**Observed behavior:**

Labels are restored recursively on whole /system/lib as seen here: https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L2251

**Installation debug log:**

[Labels before and after installing Open Gapps](http://hastebin.com/ucecahiyom.pl)

### PR DESCRIPTION
**Pull request by luca020400**
Fixes #355

Changes:
- Remove ch_con_recursive function
- Don't recursively set context in /system/*

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
You are quick @luca020400  Thanks!

+2 from me.

**Comment by luca020400** [comment]
Also most of the code under "Fix Permissions" should be applied only for the new files added by opengapps
Changing perms recursively is pretty dangerous

**Comment by luca020400** [comment]
Updated link in commit message to point at aosp

**Comment by mfonville** [comment]
Hey, thanks for your PR; I will look into the issue, but I will need to include a bit more changes, because some contexts do have to be set as not all recoveries let them nicely inherit it from the parent folder.

Instead of a full-recursive I think I will just set them only on the files the script did install

**Comment by jumoog** [comment]
any updates?

**Comment by TheCrazyLex** [comment]
@mfonville @luca020400  As an idea: Would probably doing "restorecon"  help?

**Comment by luca020400** [comment]
@TheCrazyLex not in recovery since it uses another selinux.bin with recovery specific rules

**Comment by jumoog** [comment]
maybe do something like

```
if [ "$API" -le "25" ]; then
 # Set contexts on all files we installed
 set_progress 0.88;
 ch_con_recursive "/system/app" "/system/framework" "/system/lib" "/system/lib64" "/system/priv-app" "/system/usr/srec" "/system/vendor/pittpatt" "/system/etc/permissions" "/system/etc/preferred-apps" "/system/addon.d";
 ch_con "$g_prop"
fi
```

**Comment by luca020400** [comment]
@jumoog what about no, changing selinux labels doesn't make sense even on <api 25
If you really want to just do that for every file you copied and not randomly in /system leading to issues android side

**Comment by jumoog** [comment]
@luca020400 yeah makes sense .. my idea was that it worked before on Android 6 😋

**Comment by luca020400** [comment]
@jumoog You shouldn't override any label in /system, hence running recursive set_con doesn't make sense

**Comment by TheCrazyLex** [comment]
@mfonville The cool @luca020400 uploaded a new commit here which would update every copied file, can you maybe test and review?

**Comment by mfonville** [comment]
I will take a look at it soon; I thought of a similar approach, so probably I can the commit

**Comment by TheCrazyLex** [comment]
Sounds great! @mfonville

**Comment by mfonville** [comment]
Thanks for your very good PR @luca020400 

sorry that it took me so long to take a good look; I have made minor small adjustment.

**Pull request merged**
