### PR TITLE
enable Google Assistant if not already enabled

### LINKED ISSUE #418: Please add option to enable the Google Assistant.
A developer was trying to submit a patch to enable the Google Assistant in Lineage OS and was told it should be done in the gapps package instead. I'm simply posting this asking for this option which should be pretty simple to do since all it needs to do is add a line to system.props the Lineage OS dev said it can be accomplished with an ini.d script. Here's the commit for the changes. I know these changes work on the OnePlus One and Nexus 7 Flo and I imagine it works on most devices as well. https://review.lineageos.org/#/c/155887/1

### PR DESCRIPTION
**Pull request by jumoog**
Fixes #418 

Changes:
- check if ro.opa.eligible_device is inside /system/build.prop if not add ro.opa.eligible_device=true to /system/build.prop

### CODE REVIEW

**Comment by LinkofHyrule89** [comment]
Oh, awesome! So is this rolling out soon? It should probably be optional with aroma and with a config file although I'm sure most people will want it.

**Comment by mfonville** [comment]
Thanks for your PR; are there any negative effects possible, if this line is used on devices that would in some way not support the assistant?

Also, are you sure the `-x` in the grep would match correctly? I would expect the whole-line match would fail, because there would be still content after the `=`

**Comment by LinkofHyrule89** [comment]
I personally can confirm this works fine (the actual line added to the build.props) on all the devices I've tried it on as well as many others using the Magisk Module that does the same thing. As far as I can tell if they don't have the newest version of the Google app the line is simply ignored. However, some people might like the regular Google Now over the Google Assistant which is why I said that it should have an option to enable or disable it on gapp flashes.

**Comment by mfonville** [comment]
After discussing a bit and identifying the expectations of users; Assistant still has some feature-regressions compared to Google Now.
So instead of making this a default, for now it would probably be the best to put this behind a keyword.
I will update the PR for this soon

**Comment by LinkofHyrule89** [comment]
I think having it optionally is how it should be done but just having the option is helpful.

**Comment by LinkofHyrule89** [comment]
Any updates on this?

**Comment by mfonville** [comment]
@LinkofHyrule89 I will get to it this week, last week got unexpectedly very busy and I had zero time :-/

**Comment by LinkofHyrule89** [comment]
OK cool hopefully this gets merged in soon 👍

**Comment by LinkofHyrule89** [comment]
@artityod the other guy is going to make changes before this is merged.

**Comment by mfonville** [comment]
This has been implemented now via
https://github.com/opengapps/opengapps/commit/f362c7157a6ad1e10b2ae1d710848430d60be253
https://github.com/opengapps/opengapps/commit/f5abced957577d287cf11f8c45228f20602d8202
https://github.com/opengapps/opengapps/commit/ea8bbff84cce0729d2659306e123f587f5d33375

and for now requires the `GoogleAssistant` keyword to add `ro.opa.eligible_device` to the `build.prop` if no prop entry is there yet.

**Comment by LinkofHyrule89** [comment]
@mfonville How do I use this with the Aroma version of gapps is it already integrated in there or do I have to wait for more code changes? If it's merged in how do I tell it to install the Google Assistant?

**Comment by mfonville** [comment]
@LinkofHyrule89 new keywords will be added to Aroma by @raulpetru

**Comment by LinkofHyrule89** [comment]
OK cool will hopefully soon I'm excited to try this out. It'll be one less magisk module to use at least.

**Comment by julianxhokaxhiu** [comment]
`GoogleAssistant` is currently not listed anywhere here: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#include-or-exclude-gapps

Can you please add it? Thank you in advance :)

**Comment by mfonville** [comment]
@julianxhokaxhiu it is listed as https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#enable-google-assistant

**Comment by julianxhokaxhiu** [comment]
Sure, but it doesn't mention in which package it exists or not. Personally I'm fladhing the smallest one, and I am wondering if I find it there. Or what it does is just a build.prop change?

**Comment by mfonville** [comment]
@julianxhokaxhiu just the build.prop change, so with any package flavor it works

**Comment by julianxhokaxhiu** [comment]
I see, thank you!

**Comment by iykequame** [comment]
still following and learning from here

**Comment by shemgp** [comment]
I can't seem to make Google Assistant to work using 20170212 gapps.  Should it suppose to show up in the logs?

**Comment by shemgp** [comment]
Found the fix myself. Google Assistant only works in Engilsh (US) and my language was different.

**Pull request closed without merging**
