### PR TITLE
installer: properly support dynamic partitions

### PR DESCRIPTION
**Pull request by jesec**
Signed-off-by: Jesse Chan <jc@lineageos.org>

### CODE REVIEW

**Comment by jesec** [comment]
Dynamic partition devices use /dev/block/mapper to stage partitions.

**Comment by mfonville** [comment]
@osm0sis could you take a look please?

**Comment by osm0sis** [comment]
Should be fine. @jesec, tested and working?

**Comment by jesec** [comment]
Yep.

**Comment by mfonville** [comment]
Ok, great, could you update the PR according to the changes that were made in https://github.com/opengapps/opengapps/pull/833 (the script template has changed)?

**Comment by jesec** [comment]
@mfonville Done.

**Comment by mfonville** [comment]
Thanks!

**Pull request merged**
