### PR TITLE
Add PA Browser to browser removal list

### PR DESCRIPTION
**Pull request by sigv**
Fixes private issue.

Changes:
- Made the installer remove the PA browser automatically.

@mfonville (because it looks like @opengapps/developers isn't really doing the thing it should be doing?)

### CODE REVIEW

**Comment by mfonville** [comment]
Could you tell me in which ROMs PA browser is bundled by default? That would be worth note in our documentation for this entry.

**Comment by sigv** [comment]
I would like to have this included as ```/system/app/PA_Browser``` is expected to be used by a specific project whose name is often abbreviated as PA. The email I used (both author and commit) should explain why I said I do not plan to comment further on the details.

**Comment by mfonville** [comment]
Ah, I only just now lookedfurther than the title of the commit message.

Would you like to update the wiki yourself or should I do that?

**Comment by sigv** [comment]
What exactly are you interested in updating in the wiki? Nothing's public yet and I would like to keep this on fairly low profile right now (that is, no wiki entries or announcements specifically for PA) while maintaining support right on release.

**Comment by mfonville** [comment]
@sigv The entry of what are considered "stock" applications to be removed. You can keep a low profile and e.g. add it to the wiki at the moment it is relevant (i.e. when you are announcing it to the public)

**Comment by sigv** [comment]
I understand that, but I was not able to find the relevant wiki page. Link me up to the page and I will make a PR when the time comes around. :wink:

**Comment by mfonville** [comment]
https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#removal-of-stock-applications

No PR necessary; everybody can directly edit :-)

**Comment by bgiesing** [comment]
Glad to hear that you know what might or might not be coming back @sigv as I was a big user of it and ran the Pushbullet channel for it and used all the themes by the lead designer.

(So secretive we can't even mention the name? LOL)

**Comment by sigv** [comment]
@mfonville Will do that when it is relevant.

@bgiesing Don't want the full name here in case the pages get indexed. If someone actually comes around and sees this, he or she knows what is up and has probably ready announcements about our "dead.. but not really" state.

:smile:

**Comment by sigv** [comment]
For full issue (PR) history, the list on the wiki page has been updated. Rejoice!

**Pull request merged**
