### PR TITLE
addon: handle mounting of {product,vendor} on A only devices

### PR DESCRIPTION
**Pull request by merothh**
* On devices with a separate product partition, addon scripts were
  not able to remove AOSP counterpart apps among possibly other
  similar issues as well

* So fix it by mounting product before we get started

* While we're at it, mount vendor too since its mounted in the
  main installer script

* Thanks to @NikhilMenghani for his input

Fixes https://github.com/opengapps/opengapps/issues/872 for A only devices.

### CODE REVIEW

**Review by nezorflame — APPROVED** [review]
LGTM

**Comment by nezorflame** [comment]
@osm0sis @mfonville please take a look as well

**Comment by osm0sis** [comment]
Only note I have would be to make sure the variables used are local only, otherwise looks good!

**Comment by mfonville** [comment]
@merothh thanks for your work!
Did you test this on devices? :-)

**Comment by merothh** [comment]
> @merothh thanks for your work!
> Did you test this on devices? :-)

Indeed i had tested the initial commit i PR-ed on **A only (Both Dynamic / Non Dynamic)**. As noted in  the last [comment](https://github.com/opengapps/opengapps/issues/872#issuecomment-682970129) i made on the [issue](https://github.com/opengapps/opengapps/issues/872)

While i was adding the changes osm0sis mentioned [above](https://github.com/opengapps/opengapps/pull/879#issuecomment-687134674), i realized how arrays weren't exactly POSIX, so i've avoided using arrays as i did initially.

The latest commit has been again tested on **A only (Both Dynamic / Non Dynamic)**, and after you guys have one last look, it seems go to go.

**Comment by merothh** [comment]
Diff between initial and latest commit

**Comment by osm0sis** [comment]
I think it looks like it'll work fine. My only thought is there's probably no reason to mount twice, just mount rw the first time for each.

Also, minor caveat, I seem to recall there being some devices that report they're slot _a even though that's only only slot on the device, but it's hard to deal with broken device setups like that.

**Comment by mfonville** [comment]
Thanks for your comments @osm0sis 
I think first mounting read-only and then trying to remount with rw is the same (good) behavior was we have in the installer script, because of some edge-cases (like emulators).

I will now merge this in, thanks @merothh !

If we can think of a way to detect the broken slot_a setups that would be very welcome in a new PR :-)

**Comment by osm0sis** [comment]
Ah yes, I always forget about the emulators

**Pull request merged**
