### PR TITLE
Fixed typo causing execution of arthmatic opperation

### PR DESCRIPTION
**Pull request by marcthe12**
Fix for #441

### CODE REVIEW

**Comment by mdmower** [comment]
I don't think this is correct. The `(( ))` is intended for += arithmetic. For example, open a mksh shell and test each of these; the first works, the second incorrectly tries to treat the contents of `(( ))` as a command.

Good: `size=0; for n in 1 1 1 1; do ((size+=n)); done; echo $size`
Bad: `size=0; for n in 1 1 1 1; do $((size+=n)); done; echo $size`

**Comment by marcthe12** [comment]
@mdmower Lineage os installer thinks to ((size+=n)) is a command and therefore crashes trying to executed it.
$((size+=n)) works for the installer

**Comment by mdmower** [comment]
Lineage os installer? I'm not familiar with such a thing.

Maybe what you're suggesting is `installer.sh` in the opengapps package is causing `/system/addon.d/70-gapps.sh` to be mangled upon installation? Would you mind pasting a copy of your `/system/addon.d/70-gapps.sh` so I can see if this command does indeed get incorrectly written?

**Comment by marcthe12** [comment]
That is in a comment in linked issue above. Also dash also causes the same error.

**Comment by marcthe12** [comment]
[Here is for more difference](http://unix.stackexchange.com/a/149916)

**Comment by mdmower** [comment]
I must be missing something here. My understanding is that `(( ))` and `$(( ))` both perform the same arithmetic. All I interpret your `$`-sign to be doing is to attempt to run the result of the arithmetic expansion as a command (notice there is no `echo` or other command in front of it).

**Comment by marcthe12** [comment]
It is a bashism. Not all shell support (( )) syntax. Strictly POSIX compliant shells like dash cause the same error as the installer (Maybe recovery and installer uses dash or ash).  $(( )) on the other work in dash, ash, ksh and bash

**Comment by mdmower** [comment]
Ok, I just tested this in `busybox sh`, and I see that it does try to run size+=n as a command. This patch is still incorrect, though, as the output of `$(( ))` (a number) is also run as a command. So a more portable solution would be to use `$(( ))` assigned to a dummy variable.

**Comment by mdmower** [comment]
In fact, this would probably work best; effectively kill the `+=`: `size=$((size+n))`

**Comment by marcthe12** [comment]
Fixed

**Comment by mdmower** [comment]
This is a good fix. You could probably squash the commits, though.

**Comment by marcthe12** [comment]
Embarasing but I am not sure how to, I think I need write acess to this repo to do that

**Comment by mdmower** [comment]
You can force push the squashed commit to your own repository's `patch-1` branch and it'll automatically pull in the update here.

**Comment by marcthe12** [comment]
ready to merge

**Comment by mfonville** [comment]
Thanks guys, your work is much appreciated :-)

**Pull request merged**
